### ISSUE TITLE
UI Flicker when loading a page, when variable-name text is being replaced with localized text

### ISSUE THREAD

**Issue by danielHalan** [panter/vue-i18next#36]
Hi, 

When a page is loaded on initial load the text shown is the variable name of the label, and after ~0,5s it is replaced with the  localized version. Which causes a flicker-effect in the UI. 

There was a ticket in i18next (https://github.com/i18next/i18next/issues/885) regarding this, where answer was to hide the text until resources are loaded, is there any way to configure this in vue-i18next? (similar to "wait" in react-i18next)

Also is there any way to reduce the amount of time before the text is loaded?

**Comment by claudiocro** [comment]
Hi,

thank for reporting!

We just released a new version 0.0.13 with a new directive `v-waitForT` that should solve your problem:
https://panter.github.io/vue-i18next/guide/directive.html#v-waitfort

The amount for time that the text need to be loaded is handled by `i18next` it self.

**Comment by laygir** [comment]
Hi @claudiocro  

Sorry for reviving this.

Does v-waitForT has much difference then v-cloak? Is this the only solution for such issue? Can I just hold the whole app until necessary resources are loaded? The fact that v-waitForT or v-cloak uses display: none, results in jumping HTML blocks caused by the removal of display: none.

**Comment by ralyodio** [comment]
I'm having this same issue with svelte-i18next library.

Flash of English before translated to local language. Kind of annoying.

I'm setting using `beforeUpdate()` hook
